# Generated by Django 4.0.1 on 2022-01-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee')),
            ],
        ),
    ]
